# -*- coding: utf-8 -*-
"""git_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r7amx52ZqATvZ8VyteQl_tjaDVGxbB9m
"""

!git init

!git add .

!git config --global uer.name "shivas24"
!git config --global user.email "shivasunkaranam@gmail.com"

!git commit -m "first file"

!git branch -M main

!git branch

!git remote add origin https://github.com/shivas24/shivas24.git

!git remote -v

!git push origin main

!git add .

!git commit -m "newfile"

!git remote set-url origin https://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@github.com/shivas24/shivas24.git

!git push -u origin main

!git clone  https://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@github.com/shivas24/shivas24.git

!git remote -v

!git status

!git init

!git status

!git remote -v

!git push -u origin main

!git status

!git fetch

!git branch main

!git log

!git reset --hard

!git push -u origin main

